steps:
  # Install dependencies and build the Next.js app
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

  # Build the Docker image and push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t', 'gcr.io/$PROJECT_ID/nextjs-app:$SHORT_SHA', '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 'gcr.io/$PROJECT_ID/nextjs-app:$SHORT_SHA'
    ]

# Deploy the container to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'nextjs-app',
      '--image', 'gcr.io/$PROJECT_ID/nextjs-app:$SHORT_SHA',
      '--platform', 'managed',
      '--region', 'us-central1',
      '--allow-unauthenticated'
    ]

images:
  - 'gcr.io/$PROJECT_ID/nextjs-app'
