name: CI/CD to GCP Cloud Run

on:
  push:
    branches:
      - main  # Deploy on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Authenticate with GCP
      run: gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS

    - name: Build Docker image
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/nextjs-app .

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy nextjs-app \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/nextjs-app \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
